### ISSUE TITLE
Recognize the Direction while swiping

### ISSUE THREAD

**Issue by johnrajahkkd** [Kicksort/KSSwipeStack#12]
Hi, Thanks for the useful library. 

There is an option to find the direction after swiping. But I couldn't find the way how to recognize the direction of cards/view while swiping. 
I tried a lot of methods. But couldn't figure out. Need help. 

Thanks

**Comment by arneson** [comment]
Hi! 
Currently the best way of getting the current direction 'when the swipe is happening' is to extend SwipableView and overrride the method 
`open func respondToSwipe(like: Bool, opacity: Float) {`
This method is fired every time a card is moved in the view.

If you need to get the direction 'outside' of you card, we would have to look at adding that functionality.

**Comment by Sundin** [comment]
Hi @johnrajahkkd! 

We just published a new version (0.4.4) where you can instead override `respondToSwipe(direction: SwipeDirection, distance: Float)` in case you need to support vertical swiping as well.

Cheers!

**Comment by Sundin** [comment]
I'm closing this issue, feel free to open it again in case you have any issues. Cheers 🍺
