### ISSUE TITLE
adding navigation controller

### ISSUE THREAD

**Issue by milligator** [Kicksort/KSSwipeStack#5]
Hi,
thanks for the project. when I started the example project it worked fine. When I embedded a navigation controller to the example project and to fit the size of the cards according to my needs, I added a new view with the desired constraints. I removed the outlet from the main view and connected the outlet to the new view and changed the custom classes too. But the cards does not position in the middle of the screen and does not swipe out the screen on incomplete swipes.

1. How can I change the size of cards to fit my needs?
2. what happens if I try to swipe 10000 cards? Does cards load at once in the memory and cause high memory usage?

Best Regards

**Comment by Sundin** [comment]
Hi @milligator! 

In `SwipeOptions` you can specify a value on `maxRenderedCards`, which controls how many cards will be loaded into the memory at once. It defaults to 5 at the moment, so memory consumption should be fine. (You can increase this value if your cards starts to take a while to appear after the first five ones).

Regarding your first question; do you have some sample code we can look at? We did some improvements regarding using custom-sized cards in v0.3.0, but probably it's not perfect yet.

**Comment by arneson** [comment]
This is now fixed in newly released version 0.3.1. (5e49332)
Thanks @milligator for your feedback.

**Comment by milligator** [comment]
@Sundin 
Just add a UIView (I call it subView) to the UIViewController and set its class to SwipeView and remove the outlet from the UIViewController and connect the swipeView outlet to the the subView.
@arneson thanks for your fix
