### ISSUE TITLE
how to swipe a card when clicked on button?

### ISSUE THREAD

**Issue by FeminaBrahmbhatt** [Kicksort/KSSwipeStack#7]
in my app I want to add yes and no button so when I click on yes button the card would remove from right side and when clicked on no button the card would remove from left side.

**Comment by Reelevant** [comment]
That kind of defeats the purpose of SwipeCards, doesn't it? :) You're looking for a transitional animation, this is an interactive tool

**Comment by FeminaBrahmbhatt** [comment]
I want to create a card just like the card in tinder which allows both ways swipe and clicking on button,actually I saw all the card view library and there is always one issue with all that and that is it does not allow scrolling in card view ,which is supported in your library but the only back feature is I am not able to implement same functionality in button.it <http://button.it/> would be great if you can do that.


Thanks,
Femina Brahmbhatt
feminabrahmbhatt6@gmail.com

**Comment by Reelevant** [comment]
Hey it's not my library, we're just happy to have access to Simon and Gustav's code :)

Regarding scrolling and swiping in the same time on the same card - perhaps you should rethink your UI, or find a different library that simply does a pre-baked animation..

For what I've learned this library gets delta cues from swipe movement, but you can probably fork it to serve your purposes and feed parametric animation into the movement detection.Just an idea..

Our current issue is the absence of swipe indicator overlay, which was projected to be implemented in the library, but I know the guys are busy enough so I won't stress them with it. We'll find a way :)

Happy New Year and have a great year of projects!

**Comment by Sundin** [comment]
Hi @FeminaBrahmbhatt!

This functionality is a piece of cake to implement! First please update the pod to v0.4.2, and then you can call `swipeView.respondToSwipe(.left)` and `swipeView.respondToSwipe(.right)` correspondingly.
