### ISSUE TITLE
Being able to programmatically trigger swipe

### ISSUE THREAD

**Issue by Shaggy13spe** [Kicksort/KSSwipeStack#8]
Not sure if this functionality already exists, but couldn't see anything to lead me in that direction. I have implemented your library and it works great, however, my card has two buttons like/dislike that need to allow the user to perform the same actions that swiping left/right would. Is this functionality built in?

**Comment by we4sz** [comment]
Closed issue on the topic  already exists #7  😄

**Comment by Shaggy13spe** [comment]
Awesome thanks! Sorry, didn't see that I had filtered on only Open issues. Great control!!!!
