### ISSUE TITLE
SwipeView link in ReadMe leads nowhere

### ISSUE THREAD

**Issue by haejinjo** [Kicksort/KSSwipeStack#9]
I'm not able to clarify what it means to put a SwipeView into my Storyboard. I wondered if it would just magically appear after installing this cocoapod but the closest thing I can find in my right sidebar is a "Swipe Gesture Recognizer".

Stuck at first step. Sad face :(

**Comment by Reelevant** [comment]
hi haejinjo, I suggest you use the KSSwipeView example provided to get a sense of how to use it. IB won't be updated afaik, but you can add a view for your cards and change its class to SwipeView

**Comment by haejinjo** [comment]
That's exactly what I realized it meant. Drag  in a plain old UIView and
change its class to SwipeView!
I was looking at the Classes folder instead of the example ViewController
in the repo, the latter of which turned out to be a lot more helpful. Than
you for the prompt reply!

**Comment by Sundin** [comment]
Glad to hear you got it working! Let us know if you encounter any more problems, or have suggestions on how to improve the documentation. Cheers! 🍺
